//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvadro
{
    using System;
    using System.Collections.Generic;
    
    //public partial class CustomerInfo
    //{
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    //    public CustomerInfo()
    //    {
    //        this.ProjectInfo = new HashSet<ProjectInfo>();
    //    }
    
    //    public string Customer { get; set; }
    //    public string Phone { get; set; }
    //    public string Bank { get; set; }
    //    public string Account { get; set; }
    //    public string INN { get; set; }
    //    public string AdressCost { get; set; }
    //    public string FioWorker { get; set; }
    //    public Nullable<int> PhoneWorker { get; set; }
    
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<ProjectInfo> ProjectInfo { get; set; }
    //}
}
