//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvadro
{
    using System;
    using System.Collections.Generic;
    
    //public partial class EmployeeInfo
    //{
    //    public long EmployeeID { get; set; }
    //    public string EmployeeName { get; set; }
    //    public string Adress { get; set; }
    //    public string District { get; set; }
    //    public int Experiance { get; set; }
    //    public System.DateTime Year { get; set; }
    //    public string Language { get; set; }
    //    public string Base { get; set; }
    //    public string Comment { get; set; }
    //    public Nullable<int> BonusAll { get; set; }
    //    public Nullable<System.DateTime> EmployeeStart { get; set; }
    //    public Nullable<System.DateTime> EmployeeStop { get; set; }
    //    public Nullable<long> ProjectID { get; set; }
    
    //    public virtual SalaryInfo SalaryInfo { get; set; }
    //    public virtual ProjectInfo ProjectInfo { get; set; }
    //}
}
