//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvadro
{
    using System;
    using System.Collections.Generic;
    
    //public partial class Participation_in_project
    //{
    //    public Nullable<long> ProjId { get; set; }
    //    public long EmpId { get; set; }
    //    public Nullable<System.DateTime> StartDate { get; set; }
    //    public Nullable<System.DateTime> StopDate { get; set; }
    
    //    public virtual EmployeeInfo EmployeeInfo { get; set; }
    //}
}
