//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvadro
{
    using System;
    using System.Collections.Generic;
    
    //public partial class Programming_Languages
    //{
    //    public long id { get; set; }
    //    public string name { get; set; }
    //    public long ProjectId { get; set; }
    
    //    public virtual ProjectInfo ProjectInfo { get; set; }
    //}
}
