//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvadro
{
    using System;
    using System.Collections.Generic;
    
    //public partial class ProjectInfo
    //{
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    //    public ProjectInfo()
    //    {
    //        this.EmployeeInfo = new HashSet<EmployeeInfo>();
    //    }
    
    //    public long ProjectID { get; set; }
    //    public string ProjectName { get; set; }
    //    public Nullable<System.DateTime> ProjectStart { get; set; }
    //    public Nullable<System.DateTime> ProjectStop { get; set; }
    //    public string Chief { get; set; }
    //    public Nullable<decimal> Cost { get; set; }
    //    public string INN { get; set; }
    
    //    public virtual CustomerInfo CustomerInfo { get; set; }
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<EmployeeInfo> EmployeeInfo { get; set; }
    //}
}
