//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvadro
{
    using System;
    using System.Collections.Generic;
    
    //public partial class SalaryInfo
    //{
    //    public decimal Salary { get; set; }
    //    public Nullable<decimal> Bonus { get; set; }
    //    public Nullable<decimal> GrossSalary { get; set; }
    //    public Nullable<decimal> Exempt { get; set; }
    //    public long EmployeeId { get; set; }
    
    //    public virtual EmployeeInfo EmployeeInfo { get; set; }
    //}
}
